POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI1ZWVjY2YxZTFhZGJlZTQ2ZTAxOThjN2MiLCJpYXQiOjE1OTI1Nzc4NDV9.jWLTMf7SkqMs6dxE0oXggopoJkpVWdvxL-qx_Ke_g8U

{
  "content": "test user note",
  "important": false
}