POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyNCIsImlkIjoiNWVlZTUxOTk4MjNkYTcyYzM0ZjRlNjRhIiwiaWF0IjoxNTkyNzA4MjQyfQ.AJVCvAnxjNYASvEctYx8KFQi2cl8cZdv1iLRN6LZDxw

{
  "title": "test blog 2",
  "author": "will palaia",
  "url": "google.com",
  "likes": -20,
  "userId": "5eed3e42488e8846ecedca8"
}